"""0002

Revision ID: 4b80d6ceafa2
Revises: e4825393c025
Create Date: 2024-02-11 14:53:55.831836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b80d6ceafa2'
down_revision: Union[str, None] = 'e4825393c025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_work', 'closed', name='taskstatus'), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('maker_id', sa.Integer(), nullable=True),
    sa.Column('maker_position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['maker_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['maker_position_id'], ['job_position.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
