"""0002

Revision ID: 5729f42672eb
Revises: 6d0432521fa9
Create Date: 2024-02-17 20:44:49.637608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5729f42672eb'
down_revision: Union[str, None] = '6d0432521fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_account', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_account', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
